src/Entity/Comptes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Comptes
 * Représente un compte localement. Un compte consiste en un identifiant et une clé.
 * Son rôle est de gérer la liste des utilisateurs.
 *
 * @ORM\Table(name="Comptes", uniqueConstraints={@ORM\UniqueConstraint(name="nom_UNIQUE", columns={"nom"})})
 * @ORM\Entity
 */
class Comptes
{
    /**
     * @var int
     *
     * @ORM\Column(name="idComptes", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idcomptes;

    /**
     * @var \Transcations
     *
     * @ORM\OneToMany(targetEntity="Transactions", mappedBy="idcompte")
     * @ORM\OrderBy({"date" = "DESC"})
     */
    private $transactions;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50, nullable=false)
     */
    private $nom;

    public function __construct(){
        $this->transactions = new ArrayCollection();
    }

    public function getIdcomptes(): ?int
    {
        return $this->idcomptes;
    }

    public function getTransactions(){
        return $this->transactions;
    }

    public function getLastTransaction(){
        return $this->transactions[0];
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function addTransaction(Transactions $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setIdcompte($this);
        }

        return $this;
    }

    public function removeTransaction(Transactions $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            if ($transaction->getIdcompte() === $this) {
                $transaction->setIdcompte(null);
            }
        }

        return $this;
    }


}

src/Form/ComptesType.php
<?php

namespace App\Form;

use App\Entity\Comptes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ComptesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Comptes::class,
        ]);
    }
}

src/Controller/ComptesController.php
<?php

namespace App\Controller;

use App\Entity\Comptes;
use App\Form\ComptesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/comptes")
 */
class ComptesController extends AbstractController
{
    /**
     * @Route("/{idcomptes}", name="comptes_show", methods={"GET"})
     */
    public function show(Comptes $compte): Response
    {
        return $this->render('comptes/show.html.twig', [
            'compte' => $compte,
        ]);
    }
}

templates/comptes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comptes{% endblock %}

{% block body %}
    <h1>Comptes</h1>

    <table class="striped">
        <tbody>
            <tr class="">
                <th scope="row">Nom</th>
                <td>{{ compte.nom }}</td>
            </tr>
            <tr class="">
                <th scope="row">Solde</th>
                {% if compte.lastTransaction.solde < 0 %}
                    <td style="color:red;"> <b>{{ compte.lastTransaction.solde }}</b></td>
                {% else %}
                    <td style="color:green;"> <b>{{ compte.lastTransaction.solde }}</b></td>
                {% endif %}
            </tr>
        </tbody>
    </table>

    <button onclick="window.location.href = '{{ path('depot',  {'compte' : compte.idcomptes}) }}';" type="button" class="btn btn-success">Déposer</button>
    <button onclick="window.location.href = '{{ path('retrait',  {'compte' : compte.idcomptes}) }}';" type="button" class="btn btn-warning">Retirer</button>

    <table class="striped">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">intitule</th>
                <th scope="col">Solde</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in compte.transactions %}
                <tr class="table-light">
                    <td>{{ transaction.datestring }}</td>
                    <td>{{ transaction.intitule }}</td>
                    <td>{{ transaction.solde }}</td>
                </tr>
            {% else %}
            <tr class="table-warning">
                <td colspan="3">Aucune transaction enregistrée.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <button onclick="window.location.href = '{{ path('login') }}';" type="button" class="btn btn-success">Déconnexion</button>
{% endblock %}